version: '3.3'

networks:
  aio:
    ipam:
      config:
        - subnet: "172.18.3.0/24"

services:

  tor-privoxy:
    container_name: tor-privoxy
    build: tor-privoxy
    restart: always
    environment:
      - IP_CHANGE_SECONDS=300
    networks:
      - aio
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8888:8888" # Privoxy

  postgres:
    container_name: postgres
    build: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - aio
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data

#  redis:
#    container_name: redis
#    build: redis
#    restart: always
#    networks:
#      - aio
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis/data:/data
#
#  rethinkdb:
#    container_name: rethinkdb
#    build: rethinkdb
#    restart: always
#    networks:
#      - aio
#    ports:
#      - "8080:8080"
#      - "28015:28015"
#    volumes:
#     - ./rethinkdb/data:/data
#
#  scrapy:
#    container_name: scrapy
#    build: scrapy
#    restart: always
#    environment:
#      - HTTP_PROXY=multitor:16379
#      - HTTPS_PROXY=multitor:16379
#    ports:
#      - "6800:6800"
#    networks:
#      - aio
#    volumes:
#      - ./scrapy:/usr/src/app
#    depends_on:
#      - postgres
#      - redis
#
##  splash:
##    container_name: splash
##    build: splash
##    restart: always
##    ports:
##      - "8050:8050"
##    networks:
##      - aio
##    volumes:
##      - ./splash/proxy-profiles:/etc/splash/proxy-profiles
##      - ./splash/js-profiles:/etc/splash/js-profiles
##      - ./splash/filters:/etc/splash/filters
##      - ./splash/lua_modules:/etc/splash/lua_modules
#
  multitor:
    container_name: multitor 
    build: multitor
    restart: always
    environment:
      - TOR_INSTANCES=20
    ports:
      - "16379:16379"
    networks:
      - aio
#
#
