version: '3.3'

networks:
  aio:
    ipam:
      config:
        - subnet: 10.18.0.0/24

services:

  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - aio
    ports:
      - "7777:7777"
      - "7778:7778"
    #volumes:
    #  - ./app/app:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:7778/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
      #dockerfile: Dockerfile_debian
    shm_size: 4gb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--auth-local=scram-sha-256 --auth-host=scram-sha-256
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - aio
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - ./data/postgres/dump:/dump
      - ./postgres/conf:/etc/postgres
      - ./data/postgres/ssl:/var/lib/postgresql/ssl:ro
      - ./data/postgres/log:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgres/postgresql.conf


  redis:
    build: redis
    restart: unless-stopped
    networks:
      - aio
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - aio
    volumes:
      - ./app/app/static:/usr/share/nginx/html/static
      - ./app/app/storage:/usr/share/nginx/html/storage
      - ./data/nginx/log:/var/log/nginx
    healthcheck:
      test: ["CMD", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  sqlite:
    build: sqlite
    restart: unless-stopped
    networks:
      - aio
    volumes:
      - ./data/sqlite:/var/sqlite

  sanic:
    build:
      context: sanic
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - aio
    ports:
      - 8000:8000
    volumes:
      - ./sanic/static:/src/app/static
      - ./sanic/templates:/src/app/templates
      - ./data/sanic/sqlite:/var/sqlite
      - ./data/sanic/uploads:/src/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

