version: '3.3'

networks:
  aio:
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  aiowebapp:
    build: app
    container_name: app
    restart: always
    networks:
      - aio
    ports:
      - "8080:8080"
    volumes:
      - ./app/app:/usr/src/app

  postgres:
    build: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - aio
    ports:
      - "5432:5432"

  redis:
    build: redis
    restart: always
    networks:
      - aio
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_ssl
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - aio
    volumes:
      - ./app/app/static:/usr/share/nginx/html/static
      - ./app/app/storage:/usr/share/nginx/html/storage
    depends_on:
      - aiowebapp

  worker:
    build: ./worker
    container_name: worker
    restart: always
    ports:
      - "5556:5556"
    networks:
      - aio
    #volumes:
    #  - ./app/app/storage:/var/storage
    #depends_on:
    #  - aiowebapp

