version: '3.3'

networks:
  aio:
    ipam:
      config:
        - subnet: 10.18.0.0/24

services:
  aiowebapp:
    build: app
    restart: always
    networks:
      - aio
    ports:
      - "8080:8080"
    volumes:
      - ./app/app:/usr/src/app

  postgres:
    build: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - aio
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - ./postgres/etc_postgres:/etc/postgres
      - ./postgres/etc_postgres-common:/etc/postges-common

  redis:
    build: redis
    restart: always
    networks:
      - aio
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - aio
    volumes:
      - ./app/app/static:/usr/share/nginx/html/static
      - ./app/app/storage:/usr/share/nginx/html/storage
    depends_on:
      - aiowebapp

