version: '3'

services:
  aiowebapp:
    build: app
    restart: always
    networks:
      - aio
    ports:
      - "8080:8080"
    volumes:
      - ./app/app:/usr/src/app

  postgres:
    build: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - aio
    ports:
      - "5432:5432"

  redis:
    build: redis
    restart: always
    networks:
      - aio
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile_ssl
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - aio
    volumes:
      - ./app/app/static:/usr/share/nginx/html/static
      - ./app/app/storage:/usr/share/nginx/html/storage
    depends_on:
      - aiowebapp

networks:
  aio:

