host: 0.0.0.0
port: 8080

postgres:
  database: crawler
  user: crawler
  password: crawler
  host: postgres
  port: 5432
  minsize: 1
  maxsize: 5

postgres_sa:
  database: app
  user: app
  password: apppw
  host: postgres
  port: 5432
  minsize: 1
  maxsize: 5

redis:
  host: redis
  port: 6379
  minsize: 1
  maxsize: 5
