host: 0.0.0.0
port: 7777

postgres:
  database: storage
  user: api
  password: apipw
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

postgres_sa:
  database: app
  user: app
  password: apppw
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

redis:
  host: localhost
  port: 6379
  minsize: 1
  maxsize: 5
