-- Setup app Database
CREATE USER app WITH PASSWORD 'apppw';
DROP DATABASE IF EXISTS app;
CREATE DATABASE app;
ALTER DATABASE app OWNER TO app;
GRANT ALL PRIVILEGES ON DATABASE app TO app;

-- Setup api Database
CREATE USER crawler WITH PASSWORD 'crawler';
CREATE DATABASE crawler;
GRANT ALL PRIVILEGES ON DATABASE crawler TO crawler;

-- Setup test Database
CREATE USER test_aioapp WITH PASSWORD 'testaioapppw';
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
ALTER DATABASE test OWNER TO test_aioapp;
GRANT ALL PRIVILEGES ON DATABASE test TO test_aioapp;
